name: First Workflow 
on: workflow_dispatch
jobs:
  first_job:  
    runs-on: ubuntu-latest
    steps:
      - name: Print greetng
        run: echo "Hello World"
      - name: print message
        run: echo "HEY THERE"
    
